In [2]:
import numpy as np

In [4]:
a = [1,2,3,4]
b = [2,3,4,5]


In [5]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [17]:
np.arange(1,10)
np.zeros(10)
np.random.randint(0,10,100)
np.linspace(1,10,10)
np.random.normal(10,4,(3,4))

array([[ 1.6938791 , 12.55731383, 11.42050685, 11.16923907],
       [ 8.98864586, 11.05824531,  8.9355213 , 11.199569  ],
       [ 4.27092332,  3.50521744,  8.92333539, 10.71758785]])

In [19]:
a = np.random.randint(10,size=5)
a

array([3, 4, 3, 6, 6])

In [20]:
a.ndim

1

In [21]:
a.shape

(5,)

In [22]:
a.size

5

In [23]:
a.dtype

dtype('int32')

In [28]:
ar = np.random.randint(1,10,size=9).reshape(3,3)
ar

array([[1, 9, 7],
       [7, 5, 5],
       [3, 1, 8]])

In [30]:
a = np.random.randint(10,size=10)
a[0]
a[0:5]
a[0]=999

In [33]:
m = np.random.randint(10,size=(3,5))
m

array([[3, 3, 6, 8, 3],
       [3, 1, 5, 6, 6],
       [6, 2, 5, 2, 5]])

In [34]:
m[0,0]
m[1,1]

1

In [35]:
m[1:3,1:3]

array([[1, 5],
       [2, 5]])

In [36]:
m[:,0]

array([3, 3, 6])

In [37]:
m[1,:]

array([3, 1, 5, 6, 6])

In [38]:
m[0:2,0:3]

array([[3, 3, 6],
       [3, 1, 5]])

In [40]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [41]:
v[1]

3

In [42]:
v[4]

12

In [43]:
#Fancy Index
catch = [1,2,3]
v[catch]

array([3, 6, 9])

In [44]:
v = np.array([1,2,3,4,5])

In [45]:
v[v>3]

array([4, 5])

In [47]:
v[v>2]

array([3, 4, 5])

In [48]:
v[v!=2]

array([1, 3, 4, 5])

In [50]:
v[v==4]

array([4])

### Matematiksel İşlemler

In [51]:
v = np.array([1,2,3,4,5])
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [52]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [53]:
v**2

array([ 1,  4,  9, 16, 25])

In [54]:
v-10

array([-9, -8, -7, -6, -5])

In [55]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [56]:
np.add(v,4)

array([5, 6, 7, 8, 9])

In [57]:
np.var(v)

2.0

In [58]:
np.min(v)

1

In [60]:
np.max(v)

5